version: '3'
services:
    php:
        build: ./php
        expose:
            - "9000"
        volumes:
            - "./php:/app/php"
        networks:
            - app_net
    nginx:
        build: ./nginx
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑nodejs和php所有服务
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射nginx配置文件
            - "./nginx/conf.d:/etc/nginx/conf.d"
            # 映射nginx日志文件
            - "./nginx/log:/var/log/nginx"
            # 映射php网关层
            - "./php:/app/php"
        networks:
            - app_net
    jenkins:
        image: jenkins:latest
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - "./jenkins/jenkins_home:/var/jenkins_home"
networks:
    # 配置docker network
    app_net:
        driver: bridge
